modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "ARR"

[[mods]]
modId = "beachparty"
version = "${version}"
displayName = "Beachparty"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
logoFile = "pack.png"

[[dependencies.beachparty]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.beachparty]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.beachparty]]
modId = "architectury"
mandatory = true
versionRange = "[6.5.77,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.beachparty]]
modId = "doapi"
mandatory = true
versionRange = "[1.1.0,)"
ordering = "AFTER"
side = "BOTH"